# 300 words from gpt
words = [
    "zone", "resident", "reservation", "ambulance", "device", "politician",
    "nutrition", "calendar", "appointment", "hostel", "diploma", "satisfaction",
    "gymnasium", "boarding pass", "tourism", "clerk", "auditor", "essay",
    "dancer", "deadline", "arrival", "actor", "tablet", "builder",
    "physician", "plumber", "responsibility", "banker", "interview", "heater",
    "intersection", "campus", "scientist", "commute", "withdrawal", "teacher",
    "reception", "curriculum", "internship", "experience", "welfare", "telephone",
    "workshop", "ferry", "police officer", "gas", "requirement", "colleague",
    "schedule", "transportation", "dormitory", "departure", "venue", "receipt",
    "pedestrian", "gym", "museum", "upload", "canteen", "consultant",
    "enquiry", "warehouse", "illness", "invoice", "lecture", "client",
    "basement", "university", "analyst", "translator", "vegetarian", "scholarship",
    "surcharge", "charger", "tutor", "rent", "employer", "blanket",
    "thesis", "transit", "password", "pillow", "professor", "catering",
    "tourist", "storage", "library", "cancellation", "attendance", "mattress",
    "luggage", "discount", "allergy", "baggage", "equipment", "electrician",
    "feedback", "budget", "citizen", "deposit", "gender", "motorcycle",
    "baker", "payment", "ingredient", "insurance", "nurse", "receptionist",
    "complaint", "update", "headache", "smartphone", "fitness", "cleaner",
    "photographer", "photography", "electricity", "tenant", "beverage", "souvenir",
    "interpreter", "surgeon", "editor", "mechanic", "specialist", "credit card",
    "theater", "monitor", "extension", "cabin", "architect", "tour guide",
    "address", "nationality", "accountant", "platform", "driver", "kettle",
    "voucher", "gardener", "cash", "pharmacy", "pharmacist", "youth",
    "car park", "aisle", "facility", "account", "reimbursement", "musician",
    "assessment", "waiter", "emergency", "visa", "calorie", "sculpture",
    "timetable", "producer", "instructor", "register", "room rate", "postage",
    "backpack", "painting", "retail", "email", "cashier", "terminal",
    "pilot", "lawyer", "roommate", "microwave", "certificate", "technician",
    "volunteer", "qualification", "owner", "designer", "farmer", "maintenance",
    "assistant", "accommodation", "utilities", "chef", "fire exit", "lecturer",
    "librarian", "rehearsal", "plumbing", "secretary", "destination", "check-in",
    "heating", "keyboard", "estate", "medication", "undergraduate", "brochure",
    "sponsorship", "broker", "sailor", "nursery", "cabin crew", "poet",
    "transfer", "manager", "supervisor", "employee", "laundry", "judge",
    "lounge", "lease", "passport", "guidebook", "speaker", "apartment",
    "faculty", "subsidy", "economist", "laboratory", "headphone", "vaccination",
    "tuition", "currency", "customer", "painter", "researcher", "access",
    "engineer", "airline", "surrounding", "carpenter", "stomachache", "cinema",
    "repair", "expense", "income", "surveillance", "training", "adapter",
    "waitress", "director", "vehicle", "wheelchair", "injury", "soldier",
    "residence", "priority", "neighbor", "overtime", "balcony", "roundabout",
    "token", "postgraduate", "download", "principal", "attachment", "assignment",
    "postcode", "visitor", "transaction", "seminar", "refund", "landlord",
    "examination", "avenue", "dentist", "psychologist", "novelist", "surname",
    "suburb", "student", "hallway", "opportunity", "cruise", "passenger",
    "revision", "corridor", "prescription", "diplomat", "salary", "butcher",
    "journalist", "suitcase", "cafeteria", "dessert", "sanitation", "bicycle",
    "fridge", "occupation", "sightseeing", "curtain", "website", "exhibition",
    "counselor", "itinerary", "gallery", "resume", "firefighter", "battery"
]

# some phrases
words = [
    "boarding pass", "business trip", "credit card", "customer service", "data analysis",
    "driving license", "emergency exit", "entry fee", "environmental protection", "family name",
    "first aid", "fitness center", "full-time job", "group booking", "health insurance",
    "identity card", "information desk", "internet access", "language exchange", "library card",
    "local resident", "lost property", "luggage claim", "membership fee", "mobile phone",
    "national holiday", "online registration", "part-time job", "parking permit", "payment method",
    "personal details", "post office", "public transport", "reference letter", "registration form",
    "recycling bin", "return ticket", "safety regulation", "student discount", "tour guide",
    "traffic rules", "travel agency", "visa application", "working hours", "writing task"
]
# 第一次听写错误
words = [
    "driving license", "first aid", "online registration", "safety regulation", "writing task"
]

# 363 words from
# https://ieltsonlinetests.com/zh-hans/listening-tips/3305564.html
words = [
    "climate variation", "fine", "expressway/freeway", "economic crisis", "change", "hard-working",
    "mall", "study lounge", "in a fit state", "broadcast", "pipe", "housemaid",
    "workaholic", "register", "tenant", "collapse", "recession", "residence",
    "staple", "washing machine", "hospitable", "skiing", "rank", "fire",
    "hire", "on sale", "pork", "electric cooker", "subway entrance", "cyberspace",
    "want ads", "extra copy", "consult", "ferry", "neighbor-hood", "interviewer",
    "recycled water", "keep down the cost", "humidity", "shopping list", "cooperation", "multimedia",
    "housekeeper", "forgetful", "publisher", "surgeon", "blaze a trail", "enroll in",
    "do odd jobs", "convenience store", "light bulb", "reading room", "compromise", "computer science",
    "editorial", "telephone booth", "keep contact", "personality", "be involved in", "balance",
    "climate-sensitive activity", "in a mess", "vacuum cleaner", "read selectively", "sink", "take a message",
    "catalogue", "periodical room", "unfurnished", "apartment/flat", "appointment", "anesthetist",
    "job hunting", "writing permission", "overweight", "overdue", "makeup exam", "get through a novel",
    "outlet", "platform", "recognition", "documentary", "department store", "leak",
    "symptom", "iron", "job-hopping", "put on reserve", "advanced course", "counter",
    "assistance", "out of stock", "fit as a fiddle", "commercial advertisement", "drop the course", "compulsory course",
    "install", "cupboard", "client", "opening/vacancy", "interviewee", "legend",
    "credit", "syllabus", "determined", "wage", "book the ticket", "furnace",
    "novel", "watch your diet", "volume", "recyclable", "out of shape", "magazine",
    "downtown", "read extensively", "lose weight", "spare room", "air conditioner", "be addicted to the book",
    "copier", "hiking", "economical", "housework", "climate trend", "perseverance",
    "prosperous", "run for", "psychology course", "server", "on business", "wear out",
    "hallway", "infectious illness", "position", "sophomore", "leisure time", "water and soil erosion",
    "financier", "campaign manager", "physician", "book reservation", "climate watch", "maintenance",
    "refrigerator/fridge", "roundtrip", "strear", "master", "waiter/waitress", "book review",
    "inflation", "horror movie", "feel under the weather", "publication", "renewable energy", "call on",
    "the student", "date", "hitch-hike", "go dutch aa", "full-time job", "baby crib",
    "hold on", "breeze", "closing time", "drop-out", "mutton", "check in",
    "quarterly", "devote to", "associate professor", "introductory course", "stationery", "hang on",
    "sewage treatment", "application letter", "infirmary", "monetary", "teaching assistant", "conductor",
    "cutlery", "deforestation rate", "paperback edition", "violence movie", "excursion", "physics",
    "have no match for", "chairman", "achievement", "index", "press", "in poor shape",
    "tv channels", "sars", "sneeze", "runny nose", "in good shape", "stomachache",
    "library card", "downpour", "branch", "buffet", "gardening", "part-time job",
    "surplus", "sideboard", "take over", "recruit", "muggy", "workload",
    "climatic anomaly", "potential", "conservation area", "get along with", "resort", "plough through",
    "snack", "allergy", "diabetes", "electronic product", "high-speed train", "done",
    "on diet", "computer course", "chain store", "struggle", "elective/optional course", "deliver",
    "opportunity", "participant", "have a temperature", "fracture", "unemployment", "election campaign",
    "dwell", "depression", "flight number", "current issue", "housewife", "burglar",
    "luxurious items", "check out", "pay phone", "climate warming", "clinic", "back issue",
    "continuous exploration", "menu", "biography", "accommodate", "alumni/alumnus", "turn down",
    "decoration", "epidemic", "transportation", "transfer", "in charge of", "grocery store",
    "resume", "crack", "in stock", "attending/chief doctor", "attitude", "proposal",
    "loaf", "bankrupt", "shelf", "regular dinner", "symbol", "performance",
    "post doctorate", "return", "appetizer", "fix the dinner", "house-warming party", "professor",
    "bird flu", "ventilation", "take the course", "keyword", "speech contest", "supervisor",
    "dental decay", "shuttle", "past the prime", "inquiry", "diligent", "motel",
    "sign up for", "dean", "heater", "sell out", "seminar", "napkin",
    "plumber", "librarian", "multiple glazing", "conflict", "gust", "customer",
    "hang up", "curriculum", "tv theater", "bachelor", "transaction", "latest number",
    "deflation", "toothache", "visa", "beef steak", "dessert", "put on weight",
    "furnished", "entertainment industry", "pioneer", "freshman", "budget", "receipt",
    "temperature", "laundry", "suburb", "express train", "periodical", "keep an eye on",
    "lecturer", "family size", "household expenses", "reference room", "travel agency", "bid",
    "complaint", "tribute", "sore throat", "impression", "beverage", "decline",
    "mineral bath", "confident", "medium", "supermarket", "overwork", "vote",
    "hacker", "the stacks", "contribution", "join for dinner", "inexperienced", "doctoral candidate",
    "make a reservation", "physical exercise", "circulation", "forecast", "digital video camera", "out of print",
    "long-distance call", "landlord/landlady", "tube/underground", "interview", "senior student", "candidate",
    "raw", "junior student", "live broadcast"
]

# 第一次听听写不认识108个
words = [
    "expressway/freeway", "study lounge", "housemaid", "workaholic", "tenant", "collapse",
    "recession", "residence", "staple", "hospitable", "skiing", "pork", 
    "blaze a trail", "do odd jobs", "convenience store", "compromise", "editorial", "telephone booth",      
    "catalogue", "periodical room", "anesthetist", "overdue", "outlet", "department store",
    "symptom", "job-hopping", "put on reserve", "out of stock", "fit as a fiddle", "syllabus",
    "wage", "furnace", "spare room", "perseverance", "prosperous", "run for",
    "on business", "wear out", "infectious illness", "sophomore", "roundtrip", 
    "inflation",    "call on",    "hitch-hike",
    "baby crib",    "breeze",    "drop-out",    "mutton",    "stationery",    "sewage treatment",
    "infirmary",    "monetary",    "conductor",    "cutlery",    "deforestation rate",    "paperback edition",
    "in poor shape",    "sneeze",    "downpour",    "buffet",    "surplus",    "sideboard",
    "recruit",    "muggy",    "plough through",    "diabetes",    "have a temperature",    "fracture",
    "dwell",    "depression",    "check out", "hung up", 
    "call on", "hitch-hike", "baby crib",  "accommodate", "turn down", "epidemic",
    "resume", "crack", "in stock", "attending/chief doctor", "loaf", "bankrupt",
    "shelf", "appetizer", "fix the dinner", "ventilation", "speech contest", "dental decay",
    "shuttle", "past the prime", "diligent", "napkin", "multiple glazing", "gust",
    "hang up", "latest number", "periodical", "household expenses", "reference room", "bid",
    "tribute", "hacker", "inexperienced", "circulation", "forecast", "out of print"
]

# 雅思哥 生词本1-176
words = [
    "consumption", "playwrights", "submission", "radical", "thorough", "diminishing",
    "diary", "exponentially", "coating", "latter", "insulating", "pharmacy",
    "carnival", "ramp", "pattern", "feminine", "prominent", "maladies",
    "taxation", "eerie", "explicit", "transcend", "augmented", "thrive",
    "contagious", "inferior", "lime", "shoulder", "stamp", "drawing",
    "sector", "ceramics", "fraud", "summit", "ascent", "compromised",
    "peasants", "ribbons", "beads", "tedious", "destruction", "niece",
    "absorbed", "whereas", "thrived", "bank", "glitch", "literacy",
    "diversify", "textiles", "bizarre", "rehearse", "genuine", "bolstered",
    "drummer", "adequate", "anticipate", "vibrant", "anticipating", "ballet",
    "composition", "proportion", "blend", "opposite", "flute", "counteract",
    "lace", "renowned", "reaffirm", "charcoal", "publicised", "trivial",
    "superior", "bedsit", "distinction", "clay", "avail", "glazes",
    "figures", "shipwrecked", "rather", "striking", "terrace", "remuneration",
    "priority", "reservations", "yacht", "odd", "distinct", "souvenirs",
    "concentrate", "respiratory", "ingredient", "undermines", "expertise", "advocates",
    "transparency", "minded", "exploitation", "altitude", "thermometer", "commissioned",
    "morale", "deterioration", "canoe", "chronological", "preserve", "exacerbated",
    "omit", "weight", "lap", "sphere", "hills", "compulsory",
    "prone", "october", "filth", "second", "hut", "traits",
    "synthetic", "reduction", "resemble", "lauded", "banquet", "necessarily",
    "aqueducts", "artistic", "persuasive", "predators", "percussion", "catered",
    "hierarchies", "intimate", "vaccinations", "warehouse", "outmoded", "agendas",
    "medicals", "infuse", "swiss", "vitamins", "wardens", "tidy",
    "abruptly", "arson", "nutrients", "masculine", "comets", "overrun",
    "complicated", "accordance", "comprehend", "connotative", "consultation", "past",
    "underpinnings", "initiative", "ethical", "marble", "coordination", "illustrator",
    "flirtation", "scraper", "obscure", "contradictory", "abusively", "lucrative",
    "implicit", "repatriation", "dementia", "clarinet", "archipelago", "solitary",
    "begs", "cope"
]

## gpt给出必须掌握的300词，反复出错的词
words = [
    "allergy", "mattress", "secretary", "welfare", "designer", "hostel",
    "sanitation", "transportation", "accountant", "pharmacist", "canteen", "principal",
    "experience", "gymnasium", "extension", "reimbursement", "itinerary", "seminar",
    "balcony"
]

# 雅思哥听写错误25
words = [
    "altitude",    "ballet",    "canoe",    "carnival",    "clay",    "comets",
    "diary",    "figures",    "flute",    "inferior",    "marble",    "necessarily",
    "october",    "pharmacy",    "predators",    "priority",    "proportion",    "shoulder",
    "souvenirs",    "superior",    "textiles",    "thermometer",    "tidy",    "vitamins",
    "whereas"
]